// brainstorm/src/partials/Note.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import React, { FC } from "react";
import { INoteWithVotes, IUser } from "../fluid-object/interfaces";

interface NoteProps extends React.AllHTMLAttributes<HTMLButtonElement> {
  count: number;
  note: INoteWithVotes;
  user: IUser;
  highlightMine: boolean;
}

export const Note: FC<NoteProps> = (props) => (
  <button
    className={
      props.note.user.id != props.user.id && props.highlightMine
        ? "note others"
        : "note"
    }
    onClick={props.onClick}
  >
    {props.count > 0 && (
      <span
        className={`note-badge ${props.note.currentUserVoted ? "voted" : ""}`}
      >
        {props.count}
      </span>
    )}
    <span className="note-text">{props.note.text}</span>
  </button>
);

// angular/brainstorm/src/app/board/note.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { INoteWithVotes, IUser } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-note',
  template: `
    <button *ngIf="note && note.user && user" class="note"
      [ngClass]="{ others: note.user.id != user.id && highlightMine }">
        <span *ngIf="count > 0" class="note-badge" [class.voted]="note.currentUserVoted">
          {{ count }}
        </span>
      <span class="note-text">{{ note.text }}</span>
    </button>  
  `
})
export class NoteComponent implements OnInit {

  @Input() note: INoteWithVotes;
  @Input() highlightMine: boolean;
  @Input() user: IUser;
  @Input() count: number;

  constructor() { }

  ngOnInit() { }

}
