// brainstorm/src/partials/Pad.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import React, { FC, useState, ChangeEvent } from "react";
import { IUser } from "../fluid-object/interfaces";
import { NoteEditor } from "./NoteEditor";
import { Button } from "./Button";
import { UserName } from "./UserName";

// Pad
interface PadProps {
  createNote: (text: string) => void;
  demo: () => string;
  user: IUser;
  users: IUser[];
  clear: () => void;
  setHighlightMine: (value: boolean) => void;
  highlightMine: boolean;
}

export const Pad: FC<PadProps> = (props) => {
  const [value, setValue] = useState<string>("");

  const createNote = () => {
    props.createNote(value);
    setValue("");
  };
  const handleHighlight = () => {
    props.setHighlightMine(!props.highlightMine);
  };

  const onNoteValueChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setValue(e.target.value);
  };

  const onNoteFocus = () => {
    if (!value.length) {
      setValue(props.demo());
    }
  };

  return (
    <div className="container">
      <div className="pad">
        <NoteEditor
          onFocus={onNoteFocus}
          value={value}
          onChange={onNoteValueChange}
          onEnter={createNote}
        />
        <Button onClick={createNote}> Share my idea </Button>
        <Button onClick={handleHighlight}>
          {props.highlightMine ? "Stop highlighting" : "Highlight my ideas"}
        </Button>
        <Button onClick={props.clear}> Tidy up </Button>
        <UserName user={props.user} userCount={props.users.length} />
      </div>
    </div>
  );
};

// angular/brainstorm/src/app/pad/pad.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Notero } from '../services/notero.dataobject';
import { IUser } from '../shared/interfaces';

@Component({
  selector: 'app-pad',
  template: `
    <div class="container">
      <div class="pad">
        <div class="note editor">
          <textarea class="note-text"
            (keydown)="onKeyDown($event)"
            (focus)="onNoteFocus($event)"
            [value]="value"
          ></textarea>
        </div>
        <button class="button" [disabled]="disabled" (click)="createNote()">Share my idea</button>
        <button class="button" [disabled]="disabled" (click)="handleHighlight()">
          {{ highlightMine ? "Stop highlighting" : "Highlight my ideas" }}
        </button>
      <app-username *ngIf="user && users" [user]="user" [userCount]="users.length"></app-username>
      </div>
    </div>
  `
})
export class PadComponent implements OnInit {
  
  @Input() model: Notero;
  @Input() user: IUser;
  @Input() users: IUser[];
  @Input() highlightMine: boolean;
  @Output() onHighlightMine = new EventEmitter<boolean>();
  value = '';
  disabled = false;

  constructor() { }

  ngOnInit() { }

  createNote() {
    this.model.createNote(this.value);
    this.value = '';
  }

  onNoteFocus(e: any) {
    if (!this.value.length) {
      this.value = this.model.createDemoNote();
    }
  }

  onKeyDown (e: any) {
    // Handle enter
    if (e.keyCode == 13 && !e.shiftKey) {
      e.preventDefault();
      this.model.createNote(this.value);
      this.value = '';
      e.target.blur();
    }
    else {
      this.value = e.target.value;
    }
  }

  handleHighlight() {
    this.highlightMine = !this.highlightMine;
    this.onHighlightMine.emit(this.highlightMine);
  }

}
