// brainstorm/src/partials/UserName.tsx
/*!
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import React, { FC } from "react";
import { IUser } from "../fluid-object/interfaces";

interface UserNameProps {
  user: IUser;
  userCount: number;
}

export const UserName: FC<UserNameProps> = (props) => (
  <div className="userName">
    <span>{props.user.name} </span>
    <span className="userCount">
      (with {props.userCount - 1} other{" "}
      {props.userCount == 2 ? "person" : "people"})
    </span>
  </div>
);

// angular/brainstorm/src/app/pad/username.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { IUser } from 'src/app/shared/interfaces';

@Component({
  selector: 'app-username',
  template: `
    <div class="userName">
      <span>{{ user.name }}</span>
      <span class="userCount">
        (with {{ userCount - 1}} 
        {{ userCount === 2 ? "person" : "people"}})
      </span>
    </div>  
  `
})
export class UsernameComponent implements OnInit {

  @Input() user: IUser;
  @Input() userCount: number;

  constructor() { }

  ngOnInit() { }

}
